### ISSUE TITLE
File Manager for rTerminal?

### ISSUE THREAD

**Issue by R4zzerYT** [Speentie8081/HardScene_Minecraft-RemoteTerminal#4]
could you add that?

**Comment by Speentie8081** [comment]
It was already added?
You need to be using the latest version and it will show Open File Manager on the panel.
Click that and it will open up a web based file manager.
You can follow the instructions on the plugin page to connect with filezilla if you want.

**Comment by R4zzerYT** [comment]
Ah sorry, i only watched the preview on spigot.

**Comment by Speentie8081** [comment]
[Here is the part of the video where the file manager is shown and used](https://www.youtube.com/watch?time_continue=149&v=4G_fGmLVM_o&feature=emb_logo)
